flowchart LR

A[Lab 04<br/>System Requirements]
B[Lab 05<br/>UI Wireframes]
C[Lab 06<br/>Technical Architecture]
D[Lab 09<br/>Responsible Design Check]
E[Lab 10<br/>MVP Implementation Sprint 1]

F[Homepage]
G[Events Page]
H[Student Dashboard]
I[Admin Dashboard]
J[Requirement Mapping]

K[Final Smart Campus Event Hub Prototype]

A --> B
B --> C
C --> D
D --> E

E --> F
E --> G
E --> H
E --> I
E --> J

F --> K
G --> K
H --> K
I --> K
J --> K
